name: build-test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    name: Set up environment
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run build script
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run end-to-end tests
        run: pnpm run test:e2e
