name: build-test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      TEST_IMAGE_SERVICE_VERSION: 0.12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - id: npm-global-dir
        name: Get NPM global directory
        shell: bash
        run: echo "dir=$(npm root -g)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        name: Check cache for test image service
        id: cache-c2pa-test-image-service
        with:
          path: '${{ steps.npm-global-dir.outputs.dir }}/c2pa-test-image-service'
          key: ${{ runner.os }}-c2pa-test-image-service-${{ env.TEST_IMAGE_SERVICE_VERSION }}

      - name: Install test image service
        run: npm install -g c2pa-test-image-service@${{ env.TEST_IMAGE_SERVICE_VERSION }}
        if: steps.cache-c2pa-test-image-service.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: pnpm install

      - name: Run code checks
        run: |
          pnpm run lint
          pnpm run check

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run build script for test output
        run: pnpm run build
        env:
          THUMBNAIL_DATA_TYPE: datauri

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run end-to-end tests
        run: npx percy exec -- playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
