name: dev-deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        type: text
        required: true

jobs:
  build-test:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          ref: ${{ inputs.branch }}

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run code checks
        run: |
          pnpm run lint
          pnpm run check

      - name: Run build script for deployment output
        run: pnpm run build

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3 bucket
        run: |
          aws s3 sync ${{ vars.DEPLOY_SOURCE_DIR }} s3://${{ vars.AWS_DEV_S3_BUCKET }} --delete

      - name: Purge Fastly cache
        run: |
          curl -i  -X POST "https://api.fastly.com/service/${{ vars.FASTLY_DEV_SERVICE_ID }}/purge_all" -H "Fastly-Key: ${{ secrets.FASTLY_PURGE_API_TOKEN }}" -H "Accept: application/json"
