name: Production deploy

on:
  workflow_dispatch:

jobs:
  build-test:
    uses: ./.github/workflows/deploy-template.yml
    with:
      aws-bucket: ${{ vars.AWS_PROD_S3_BUCKET }}
      aws-region: ${{ vars.AWS_REGION }}
      deploy-source-dir: ${{ vars.DEPLOY_SOURCE_DIR }}
      fastly-service-id: ${{ vars.FASTLY_PROD_SERVICE_ID }}
      site-config-json: '{ "env": "prod", "features": ["homepage"] }'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
      fastly-purge-api-token: ${{ secrets.FASTLY_PURGE_API_TOKEN }}
      mapbox-token: ${{ secrets.VITE_MAPBOX_TOKEN }}
