name: stage-deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run code checks
        run: |
          pnpm run lint
          pnpm run check

      - name: Run build script for deployment output
        run: pnpm run build

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGE_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3 bucket
        run: |
          aws s3 sync ${{ vars.DEPLOY_SOURCE_DIR }} s3://${{ vars.AWS_STAGE_S3_BUCKET }} --delete
